### ISSUE TITLE
Unused Global Variables.

### ISSUE THREAD

**Issue by bolazec** [Alex-Rafter/typeCurve#1]
The first 4 lines of typeCurve.js should probably be deleted
as these global variables are not used now.

```
//Set interpolator variables and default vaules for the big and small screen sizes
let smallScreen = 320;
let bigScreen = 1500;
let smallFont, bigFont;

```

**Comment by Alex-Rafter** [comment]
Have updated these now in branch 1. I've re-written with use of objects for landscape and portrait screens. The properties are pulled in as arguments in makeInterpolator() so they are in use now.
