### ISSUE TITLE
Potential querySelector bug

### ISSUE THREAD

**Issue by mflorence99** [Alex-Rafter/typeCurve#13]
Let's assume you adopt my [optimization suggestion](https://github.com/Alex-Rafter/typeCurve/issues/12). But even if you don't, the same potential bug exists for the `querySelectorAll` call in the original code.

The problem is that by calling `querySelector` in open code, you don't have a lot of control over when it is executed. It could be executed, for example, _before_ the document is fully loaded and so the selector you're looking for won't be found.

It is much safer to make the `querySelector` call just where you need it.

```js
function changeFontSize() {
  ...
  const theGrid = document.querySelector('#theGrid');
  theGrid.style.fontSize = `${x}px`;
}
```

**Comment by Alex-Rafter** [comment]
That's updated now in branch 1. I'd not thought about this before but it makes a lot of sense. My approach was to declare all the variables i'd use first / at the top but i hadn’t thought about the fact that i would need to ensure the DOM is loaded first before the querySelector calls.
