### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by mflorence99** [Alex-Rafter/typeCurve#2]
Because in general you need to accommodate file systems that are either case-sensitive or case-insensitive, file names in a project are by convention all lowercase. CamelCase names are mapped to kebab-case. So `typeCurve.js` becomes `type-curve.js`. 

BTW, only old-timey C and Ruby programmers use snake_case!

Especially when you are publishing on GitHub, you don't know if a dev who wants to use your code works on Windows, Mac or Linux.

You might extend this suggestion to include the name of the repo as well, as the repo name becomes a directory on your local file system.

**Comment by Alex-Rafter** [comment]
Have updated the repo name, and the file naming in branch 1 now to kebab-case.

**Comment by mflorence99** [comment]
Looks good!
