### ISSUE TITLE
Strongly consider using ESLint

### ISSUE THREAD

**Issue by mflorence99** [Alex-Rafter/typeCurve#3]
[ESLint](https://eslint.org/) and its [VS Code](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) plug-in will really help ensure a consistent style and one that conforms to standard use. I'll leave you to follow up on the details - especially how to configure ESLint - but let me know if you need help.

Here's a few things I saw in `typeCurve.js` that it would catch for you.

`let smallScreen = 320;` Use `const` instead of `let` where the variable will not change.

`const letterForms = document.querySelectorAll('.letterForm');` Use either single or double quotes consistently.

`if(screenOrientation === 'landscape-primary') {` Mandatory space between `if`, `for` etc and `(`.

`x+"px"` Space required either side of operators.

`for(i = 0; i < letterForms.length; i++){` mandatory space between `)` and `{`.

```js
  if (t <= smallScreen) {
      return smallFont;
  }; // no ; needed here
```

Using ESLint (and [stylint](https://github.com/Alex-Rafter/typeCurve/issues/9)) is going to mean you'll need to create a `package.json` and other config files as required, and then commit them as a part of your project. For another dev to use your code, it is standard for them to have to do this:

```sh
git clone ...
npm install
```

To create a `package.json` from scratch one good way is to run `npm init`. See [Creating a package.json file](https://docs.npmjs.com/creating-a-package-json-file).

ESLint has good [install instructions](https://www.npmjs.com/package/eslint#installation-and-usage). You'll install it as a 'dev dependency' to your project with `npm install eslint --save-dev`. This means that the dependency need only be present during development, not at run time.

All dependencies are kept in a `node_modules` directory. Be sure to create a `.gitignore` file and commit it ensure that `node_modules` and all its contents are not themselves committed. The `.gitignore` file will have at least this one line:

```
node_modules
```

When you later start to use Jest for testing, you'll install it in this same way and not globally as your Dad did to get started.

**Comment by Alex-Rafter** [comment]
Have set up ESLint now. Had a bit of trouble with this to start. My files are saved locally in a dropbox-connected folder, and i found that i wasn't able to get ESLint set up while using this directory? When i set up a new project outside of this it worked much better. 

I need to spend quite a bit more time digging in to ESLint now i think. Experimented with checks using different formatting options but i don't think i've gone past the surface of what it's capable of yet.

Thanks for heads up on this one, looks really useful!

**Comment by mflorence99** [comment]
Interesting about dropbox, I wonder why? Yes, I agree configuring ESLint is harder than it shoud be but well worth while
