### ISSUE TITLE
Arrow function inside makeInterpolator

### ISSUE THREAD

**Issue by mflorence99** [Alex-Rafter/typeCurve#5]
Now you know all about arrow functions, you can replace `interpFont` with one.

```js
return t => {
  ...
};
```

This code has the advantage that it obeys a good principle: never name anything that can safely be left anonymous. Proper naming IMO is one of the most difficult and important programming tasks, so best not to do it if you don't have to.

**Comment by Alex-Rafter** [comment]
This is updated now in branch 1. I plan to play around with the arrow function syntax more from here.
