### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by mflorence99** [Alex-Rafter/typeCurve#6]
Modern JavaScript coding prefers [String Interpolation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) to concatenation.

So instead of `x + "px"` code `` `${x}px` ``.

Note the backticks.

**Comment by Alex-Rafter** [comment]
This was a really cool suggestion. I hadn't heard of string interpolation so this is new to me. Need to experiment more now outside of type-curve.

**Comment by mflorence99** [comment]
Looks good
