### ISSUE TITLE
Strongly consider using stylint

### ISSUE THREAD

**Issue by mflorence99** [Alex-Rafter/typeCurve#9]
[stylint](https://stylelint.io/) and its [VSCode plugin](https://marketplace.visualstudio.com/items?itemName=HaaLeo.vscode-stylint) will help keep you CSS consistent and standard, just like ESLint does for JavaScript.

All the install notes for [ESLint](https://github.com/Alex-Rafter/typeCurve/issues/3) apply to stylint.

In the interests of transparency, I should say that I have not used it myself, but I would if I were writing code now!

**Comment by Alex-Rafter** [comment]
Have downloaded and had a bit of a play around with this. As with ESLint, i definitely need to dig in quite a bit to get the most from this yet. Really useful suggestion this one!

**Comment by mflorence99** [comment]
I've been using it in my VSCode Lintel extension. I like its "auto fix" capability. So I've enabled a rule that says my CSS properties have to be alphabetical and if they aren't, it fixes that on save! There's a VSCode setting you have to make, but that was documented.
